---
- name: Deploy application
  hosts: webservers
  gather_facts: no
  tasks:
    - name: Run container
      community.docker.docker_container:
        name: hexlet-devops-project-lvl2
        image: redmine
        published_ports:
          - 80:3000
        restart_policy: always
        restart: yes
        container_default_behavior: no_defaults
        pull: yes
        env:
          REDMINE_DB_PASSWORD: "{{ db_password }}"
          REDMINE_DB_POSTGRES: "{{ db_host }}"
          REDMINE_DB_DATABASE: "{{ db_name }}"
          REDMINE_DB_USERNAME: "{{ db_username }}"
          REDMINE_DB_PORT: "{{ db_port }}"
