---
- name: Prepare webservers
  hosts: all
  gather_facts: yes
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name: python3-pip
        update_cache: yes

    - name: Install Docker Module for Python
      ansible.builtin.pip:
        name: docker

    - name: Install Datatog Module for Python
      ansible.builtin.pip:
        name: datadog
